:: NGRAM size 3 with UNKNOWN label filled up (k5)
python .\normalizer.py "C:\temp\Batch_4\NGRAMS\NGRAMS_3_WL_UNK.CSV" "C:\temp\Batch_4\Folds\NG3_k5\FOLDS_k5_1" "5" "False"
python .\normalizer.py "C:\temp\Batch_4\NGRAMS\NGRAMS_3_WL_UNK.CSV" "C:\temp\Batch_4\Folds\NG3_k5\FOLDS_k5_2" "5" "False"
python .\normalizer.py "C:\temp\Batch_4\NGRAMS\NGRAMS_3_WL_UNK.CSV" "C:\temp\Batch_4\Folds\NG3_k5\FOLDS_k5_3" "5" "False"
python .\normalizer.py "C:\temp\Batch_4\NGRAMS\NGRAMS_3_WL_UNK.CSV" "C:\temp\Batch_4\Folds\NG3_k5\FOLDS_k5_4" "5" "False"
python .\normalizer.py "C:\temp\Batch_4\NGRAMS\NGRAMS_3_WL_UNK.CSV" "C:\temp\Batch_4\Folds\NG3_k5\FOLDS_k5_5" "5" "False"
:: NGRAM size 4 with UNKNOWN label filled up (k5)
python .\normalizer.py "C:\temp\Batch_4\NGRAMS\NGRAMS_4_WL_UNK.CSV" "C:\temp\Batch_4\Folds\NG4_k5\FOLDS_k5_1" "5" "False"
python .\normalizer.py "C:\temp\Batch_4\NGRAMS\NGRAMS_4_WL_UNK.CSV" "C:\temp\Batch_4\Folds\NG4_k5\FOLDS_k5_2" "5" "False"
python .\normalizer.py "C:\temp\Batch_4\NGRAMS\NGRAMS_4_WL_UNK.CSV" "C:\temp\Batch_4\Folds\NG4_k5\FOLDS_k5_3" "5" "False"
python .\normalizer.py "C:\temp\Batch_4\NGRAMS\NGRAMS_4_WL_UNK.CSV" "C:\temp\Batch_4\Folds\NG4_k5\FOLDS_k5_4" "5" "False"
python .\normalizer.py "C:\temp\Batch_4\NGRAMS\NGRAMS_4_WL_UNK.CSV" "C:\temp\Batch_4\Folds\NG4_k5\FOLDS_k5_5" "5" "False"
:: NGRAM size 3 with UNKNOWN label filled up and split by document (k10)
python .\normalizer.py "C:\temp\Batch_4\NGRAMS\NGRAMS_3_WL_UNK.CSV" "C:\temp\Batch_4\Folds\NG3_k10\FOLDS_k10_1" "10" "True"
python .\normalizer.py "C:\temp\Batch_4\NGRAMS\NGRAMS_3_WL_UNK.CSV" "C:\temp\Batch_4\Folds\NG3_k10\FOLDS_k10_2" "10" "True"
python .\normalizer.py "C:\temp\Batch_4\NGRAMS\NGRAMS_3_WL_UNK.CSV" "C:\temp\Batch_4\Folds\NG3_k10\FOLDS_k10_3" "10" "True"
python .\normalizer.py "C:\temp\Batch_4\NGRAMS\NGRAMS_3_WL_UNK.CSV" "C:\temp\Batch_4\Folds\NG3_k10\FOLDS_k10_4" "10" "True"
python .\normalizer.py "C:\temp\Batch_4\NGRAMS\NGRAMS_3_WL_UNK.CSV" "C:\temp\Batch_4\Folds\NG3_k10\FOLDS_k10_5" "10" "True"
:: NGRAM size 4 with UNKNOWN label filled up and split by document (k10)
python .\normalizer.py "C:\temp\Batch_4\NGRAMS\NGRAMS_4_WL_UNK.CSV" "C:\temp\Batch_4\Folds\NG4_k10\FOLDS_k10_1" "10" "True"
python .\normalizer.py "C:\temp\Batch_4\NGRAMS\NGRAMS_4_WL_UNK.CSV" "C:\temp\Batch_4\Folds\NG4_k10\FOLDS_k10_2" "10" "True"
python .\normalizer.py "C:\temp\Batch_4\NGRAMS\NGRAMS_4_WL_UNK.CSV" "C:\temp\Batch_4\Folds\NG4_k10\FOLDS_k10_3" "10" "True"
python .\normalizer.py "C:\temp\Batch_4\NGRAMS\NGRAMS_4_WL_UNK.CSV" "C:\temp\Batch_4\Folds\NG4_k10\FOLDS_k10_4" "10" "True"
python .\normalizer.py "C:\temp\Batch_4\NGRAMS\NGRAMS_4_WL_UNK.CSV" "C:\temp\Batch_4\Folds\NG4_k10\FOLDS_k10_5" "10" "True"
:: NGRAM size 3 with UNKNOWN label filled up and where letters are replaced by 'x' (k5)
python .\normalizer.py "C:\temp\Batch_4\NGRAMS\NGRAMS_3_WL_X_UNK.CSV" "C:\temp\Batch_4\Folds\NG3_X_k5\FOLDS_k5_1" "5" "False"
python .\normalizer.py "C:\temp\Batch_4\NGRAMS\NGRAMS_3_WL_X_UNK.CSV" "C:\temp\Batch_4\Folds\NG3_X_k5\FOLDS_k5_2" "5" "False"
python .\normalizer.py "C:\temp\Batch_4\NGRAMS\NGRAMS_3_WL_X_UNK.CSV" "C:\temp\Batch_4\Folds\NG3_X_k5\FOLDS_k5_3" "5" "False"
python .\normalizer.py "C:\temp\Batch_4\NGRAMS\NGRAMS_3_WL_X_UNK.CSV" "C:\temp\Batch_4\Folds\NG3_X_k5\FOLDS_k5_4" "5" "False"
python .\normalizer.py "C:\temp\Batch_4\NGRAMS\NGRAMS_3_WL_X_UNK.CSV" "C:\temp\Batch_4\Folds\NG3_X_k5\FOLDS_k5_5" "5" "False"
:: NGRAM size 4 with UNKNOWN label filled up and where letters are replaced by 'x' (k5)
python .\normalizer.py "C:\temp\Batch_4\NGRAMS\NGRAMS_4_WL_X_UNK.CSV" "C:\temp\Batch_4\Folds\NG4_X_k5\FOLDS_k5_1" "5" "False"
python .\normalizer.py "C:\temp\Batch_4\NGRAMS\NGRAMS_4_WL_X_UNK.CSV" "C:\temp\Batch_4\Folds\NG4_X_k5\FOLDS_k5_2" "5" "False"
python .\normalizer.py "C:\temp\Batch_4\NGRAMS\NGRAMS_4_WL_X_UNK.CSV" "C:\temp\Batch_4\Folds\NG4_X_k5\FOLDS_k5_3" "5" "False"
python .\normalizer.py "C:\temp\Batch_4\NGRAMS\NGRAMS_4_WL_X_UNK.CSV" "C:\temp\Batch_4\Folds\NG4_X_k5\FOLDS_k5_4" "5" "False"
python .\normalizer.py "C:\temp\Batch_4\NGRAMS\NGRAMS_4_WL_X_UNK.CSV" "C:\temp\Batch_4\Folds\NG4_X_k5\FOLDS_k5_5" "5" "False"
:: NGRAM size 3 with UNKNOWN label filled up and split by document and where letters are replaced by 'x' (k10)
python .\normalizer.py "C:\temp\Batch_4\NGRAMS\NGRAMS_3_WL_X_UNK.CSV" "C:\temp\Batch_4\Folds\NG3_X_k10\FOLDS_k10_1" "10" "True"
python .\normalizer.py "C:\temp\Batch_4\NGRAMS\NGRAMS_3_WL_X_UNK.CSV" "C:\temp\Batch_4\Folds\NG3_X_k10\FOLDS_k10_2" "10" "True"
python .\normalizer.py "C:\temp\Batch_4\NGRAMS\NGRAMS_3_WL_X_UNK.CSV" "C:\temp\Batch_4\Folds\NG3_X_k10\FOLDS_k10_3" "10" "True"
python .\normalizer.py "C:\temp\Batch_4\NGRAMS\NGRAMS_3_WL_X_UNK.CSV" "C:\temp\Batch_4\Folds\NG3_X_k10\FOLDS_k10_4" "10" "True"
python .\normalizer.py "C:\temp\Batch_4\NGRAMS\NGRAMS_3_WL_X_UNK.CSV" "C:\temp\Batch_4\Folds\NG3_X_k10\FOLDS_k10_5" "10" "True"
:: NGRAM size 4 with UNKNOWN label filled up and split by document and where letters are replaced by 'x' (k10)
python .\normalizer.py "C:\temp\Batch_4\NGRAMS\NGRAMS_4_WL_X_UNK.CSV" "C:\temp\Batch_4\Folds\NG4_X_k10\FOLDS_k10_1" "10" "True"
python .\normalizer.py "C:\temp\Batch_4\NGRAMS\NGRAMS_4_WL_X_UNK.CSV" "C:\temp\Batch_4\Folds\NG4_X_k10\FOLDS_k10_2" "10" "True"
python .\normalizer.py "C:\temp\Batch_4\NGRAMS\NGRAMS_4_WL_X_UNK.CSV" "C:\temp\Batch_4\Folds\NG4_X_k10\FOLDS_k10_3" "10" "True"
python .\normalizer.py "C:\temp\Batch_4\NGRAMS\NGRAMS_4_WL_X_UNK.CSV" "C:\temp\Batch_4\Folds\NG4_X_k10\FOLDS_k10_4" "10" "True"
python .\normalizer.py "C:\temp\Batch_4\NGRAMS\NGRAMS_4_WL_X_UNK.CSV" "C:\temp\Batch_4\Folds\NG4_X_k10\FOLDS_k10_5" "10" "True"
