:: NGRAMS size 3 filled up with UNKNOWN labels (k5)
python ..\code\nmt_runner.py "C:\Users\Admin\PycharmProjects\pyml\nmt" "C:\temp\Batch_5\Folds\NG3_k5\FOLDS_k5_1" "FOLD" "C:\temp\Batch_5\Vocab\ngrams3_wl" "C:\temp\Batch_5\Embeddings\Embed\NG3\vocab_glove" "C:\Users\Admin\PycharmProjects\pyml\code\file_compare.py"
python ..\code\nmt_runner.py "C:\Users\Admin\PycharmProjects\pyml\nmt" "C:\temp\Batch_5\Folds\NG3_k5\FOLDS_k5_2" "FOLD" "C:\temp\Batch_5\Vocab\ngrams3_wl" "C:\temp\Batch_5\Embeddings\Embed\NG3\vocab_glove" "C:\Users\Admin\PycharmProjects\pyml\code\file_compare.py"
python ..\code\nmt_runner.py "C:\Users\Admin\PycharmProjects\pyml\nmt" "C:\temp\Batch_5\Folds\NG3_k5\FOLDS_k5_3" "FOLD" "C:\temp\Batch_5\Vocab\ngrams3_wl" "C:\temp\Batch_5\Embeddings\Embed\NG3\vocab_glove" "C:\Users\Admin\PycharmProjects\pyml\code\file_compare.py"
python ..\code\nmt_runner.py "C:\Users\Admin\PycharmProjects\pyml\nmt" "C:\temp\Batch_5\Folds\NG3_k5\FOLDS_k5_4" "FOLD" "C:\temp\Batch_5\Vocab\ngrams3_wl" "C:\temp\Batch_5\Embeddings\Embed\NG3\vocab_glove" "C:\Users\Admin\PycharmProjects\pyml\code\file_compare.py"
python ..\code\nmt_runner.py "C:\Users\Admin\PycharmProjects\pyml\nmt" "C:\temp\Batch_5\Folds\NG3_k5\FOLDS_k5_5" "FOLD" "C:\temp\Batch_5\Vocab\ngrams3_wl" "C:\temp\Batch_5\Embeddings\Embed\NG3\vocab_glove" "C:\Users\Admin\PycharmProjects\pyml\code\file_compare.py"
:: NGRAMS size 4 filled up with UNKNOWN labels (k5)
python ..\code\nmt_runner.py "C:\Users\Admin\PycharmProjects\pyml\nmt" "C:\temp\Batch_5\Folds\NG4_k5\FOLDS_k5_1" "FOLD" "C:\temp\Batch_5\Vocab\ngrams4_wl" "C:\temp\Batch_5\Embeddings\Embed\NG4\vocab_glove" "C:\Users\Admin\PycharmProjects\pyml\code\file_compare.py"
python ..\code\nmt_runner.py "C:\Users\Admin\PycharmProjects\pyml\nmt" "C:\temp\Batch_5\Folds\NG4_k5\FOLDS_k5_2" "FOLD" "C:\temp\Batch_5\Vocab\ngrams4_wl" "C:\temp\Batch_5\Embeddings\Embed\NG4\vocab_glove" "C:\Users\Admin\PycharmProjects\pyml\code\file_compare.py"
python ..\code\nmt_runner.py "C:\Users\Admin\PycharmProjects\pyml\nmt" "C:\temp\Batch_5\Folds\NG4_k5\FOLDS_k5_3" "FOLD" "C:\temp\Batch_5\Vocab\ngrams4_wl" "C:\temp\Batch_5\Embeddings\Embed\NG4\vocab_glove" "C:\Users\Admin\PycharmProjects\pyml\code\file_compare.py"
python ..\code\nmt_runner.py "C:\Users\Admin\PycharmProjects\pyml\nmt" "C:\temp\Batch_5\Folds\NG4_k5\FOLDS_k5_4" "FOLD" "C:\temp\Batch_5\Vocab\ngrams4_wl" "C:\temp\Batch_5\Embeddings\Embed\NG4\vocab_glove" "C:\Users\Admin\PycharmProjects\pyml\code\file_compare.py"
python ..\code\nmt_runner.py "C:\Users\Admin\PycharmProjects\pyml\nmt" "C:\temp\Batch_5\Folds\NG4_k5\FOLDS_k5_5" "FOLD" "C:\temp\Batch_5\Vocab\ngrams4_wl" "C:\temp\Batch_5\Embeddings\Embed\NG4\vocab_glove" "C:\Users\Admin\PycharmProjects\pyml\code\file_compare.py"
:: NGRAMS size 3 filled up with UNKNOWN labels and where letters are replaced by 'x' (k5)
python ..\code\nmt_runner.py "C:\Users\Admin\PycharmProjects\pyml\nmt" "C:\temp\Batch_5\Folds\NG3_X_k5\FOLDS_k5_1" "FOLD" "C:\temp\Batch_5\Vocab_X\ngrams3_wl" "" "C:\Users\Admin\PycharmProjects\pyml\code\file_compare.py"
python ..\code\nmt_runner.py "C:\Users\Admin\PycharmProjects\pyml\nmt" "C:\temp\Batch_5\Folds\NG3_X_k5\FOLDS_k5_2" "FOLD" "C:\temp\Batch_5\Vocab_X\ngrams3_wl" "" "C:\Users\Admin\PycharmProjects\pyml\code\file_compare.py"
python ..\code\nmt_runner.py "C:\Users\Admin\PycharmProjects\pyml\nmt" "C:\temp\Batch_5\Folds\NG3_X_k5\FOLDS_k5_3" "FOLD" "C:\temp\Batch_5\Vocab_X\ngrams3_wl" "" "C:\Users\Admin\PycharmProjects\pyml\code\file_compare.py"
python ..\code\nmt_runner.py "C:\Users\Admin\PycharmProjects\pyml\nmt" "C:\temp\Batch_5\Folds\NG3_X_k5\FOLDS_k5_4" "FOLD" "C:\temp\Batch_5\Vocab_X\ngrams3_wl" "" "C:\Users\Admin\PycharmProjects\pyml\code\file_compare.py"
python ..\code\nmt_runner.py "C:\Users\Admin\PycharmProjects\pyml\nmt" "C:\temp\Batch_5\Folds\NG3_X_k5\FOLDS_k5_5" "FOLD" "C:\temp\Batch_5\Vocab_X\ngrams3_wl" "" "C:\Users\Admin\PycharmProjects\pyml\code\file_compare.py"
:: NGRAMS size 4 filled up with UNKNOWN labels and where letters are replaced by 'x' (k5)
python ..\code\nmt_runner.py "C:\Users\Admin\PycharmProjects\pyml\nmt" "C:\temp\Batch_5\Folds\NG4_X_k5\FOLDS_k5_1" "FOLD" "C:\temp\Batch_5\Vocab_X\ngrams4_wl" "" "C:\Users\Admin\PycharmProjects\pyml\code\file_compare.py"
python ..\code\nmt_runner.py "C:\Users\Admin\PycharmProjects\pyml\nmt" "C:\temp\Batch_5\Folds\NG4_X_k5\FOLDS_k5_2" "FOLD" "C:\temp\Batch_5\Vocab_X\ngrams4_wl" "" "C:\Users\Admin\PycharmProjects\pyml\code\file_compare.py"
python ..\code\nmt_runner.py "C:\Users\Admin\PycharmProjects\pyml\nmt" "C:\temp\Batch_5\Folds\NG4_X_k5\FOLDS_k5_3" "FOLD" "C:\temp\Batch_5\Vocab_X\ngrams4_wl" "" "C:\Users\Admin\PycharmProjects\pyml\code\file_compare.py"
python ..\code\nmt_runner.py "C:\Users\Admin\PycharmProjects\pyml\nmt" "C:\temp\Batch_5\Folds\NG4_X_k5\FOLDS_k5_4" "FOLD" "C:\temp\Batch_5\Vocab_X\ngrams4_wl" "" "C:\Users\Admin\PycharmProjects\pyml\code\file_compare.py"
python ..\code\nmt_runner.py "C:\Users\Admin\PycharmProjects\pyml\nmt" "C:\temp\Batch_5\Folds\NG4_X_k5\FOLDS_k5_5" "FOLD" "C:\temp\Batch_5\Vocab_X\ngrams4_wl" "" "C:\Users\Admin\PycharmProjects\pyml\code\file_compare.py"
